import json
import time
from copy import deepcopy
from datetime import datetime, timezone
from pathlib import Path
from uuid import uuid4

from flask import Flask, jsonify, request
from flask_limiter import Limiter
from flask_limiter.errors import RateLimitExceeded
from flask_limiter.util import get_remote_address

import signals
from signals import SignalError


app = Flask(__name__)
limiter = Limiter(
    get_remote_address,
    app=app,
    default_limits=[],
    storage_uri="memory://",
)

BASE_DIR = Path(__file__).resolve().parent
DATA_DIR = BASE_DIR / "data"
AUDIT_LOG_PATH = DATA_DIR / "audit_log.json"
LLM_WEIGHT = 0.7
STYLO_WEIGHT = 0.3
AI_THRESHOLD = 0.75
HUMAN_THRESHOLD = 0.40
SHORT_INPUT_MAX_P_AI = AI_THRESHOLD - 0.001
SHORT_INPUT_MIN_P_AI = HUMAN_THRESHOLD
LABELS = {
    "likely_ai": (
        "**🤖 Likely AI-generated.** Our automated analysis found strong signals that this text "
        "was produced by an AI system. This is an automated assessment and is not guaranteed to be "
        "correct. If you are the creator and believe this is wrong, you can appeal this result."
    ),
    "likely_human": (
        "**✍️ Likely human-written.** Our automated analysis found strong signals that a person "
        "wrote this text, with no meaningful indication of AI generation."
    ),
    "uncertain": (
        "**❓ Origin uncertain.** Our system could not confidently determine whether this text was "
        "written by a person or generated by AI. Please treat this result as inconclusive. If "
        "you are the creator, you can appeal to have it reviewed."
    ),
}


def utc_timestamp():
    return datetime.now(timezone.utc).isoformat(timespec="milliseconds").replace("+00:00", "Z")


def clamp_score(score):
    score = float(score)
    if score < 0 or score > 1:
        raise ValueError("score must be between 0 and 1")
    return score


def combine_scores(llm_ai_likelihood, stylo_ai_likelihood):
    llm_score = clamp_score(llm_ai_likelihood)
    stylo_score = clamp_score(stylo_ai_likelihood)
    return round((LLM_WEIGHT * llm_score) + (STYLO_WEIGHT * stylo_score), 3)


def p_ai_for_short_input(llm_ai_likelihood):
    midpoint_blend = (clamp_score(llm_ai_likelihood) + 0.50) / 2
    guarded = max(SHORT_INPUT_MIN_P_AI, min(SHORT_INPUT_MAX_P_AI, midpoint_blend))
    return round(guarded, 3)


def p_ai_for_degraded_stylometry(stylo_ai_likelihood, short_input_guard=False):
    if short_input_guard:
        return 0.500

    stylo_score = clamp_score(stylo_ai_likelihood)
    guarded = max(SHORT_INPUT_MIN_P_AI, min(SHORT_INPUT_MAX_P_AI, stylo_score))
    return round(guarded, 3)


def confidence_from_p_ai(p_ai):
    p_ai = clamp_score(p_ai)
    return round(max(p_ai, 1 - p_ai), 3)


def attribution_from_p_ai(p_ai):
    if p_ai >= AI_THRESHOLD:
        return "likely_ai"
    if p_ai >= HUMAN_THRESHOLD:
        return "uncertain"
    return "likely_human"


def label_from_attribution(attribution):
    return LABELS[attribution]


@app.errorhandler(RateLimitExceeded)
def handle_rate_limit(error):
    return jsonify({"error": "Rate limit exceeded. Try again later."}), 429


def reason_from_signals(llm_result, stylo_result, degraded=False, short_input_guard=False):
    if degraded:
        llm_reason = "LLM signal unavailable after retries"
    else:
        llm_reason = llm_result["rationale"]

    metrics = stylo_result["metrics"]
    guard_note = (
        " Short-input guard applied; stylometry is recorded but not treated as reliable evidence."
        if short_input_guard
        else ""
    )
    return (
        f"LLM: {llm_reason} "
        f"Stylometry: score={stylo_result['ai_likelihood']}, "
        f"TTR={metrics['type_token_ratio']}, "
        f"sentence_std={metrics['sentence_length_std']}, "
        f"avg_word_len={metrics['avg_word_length']}. "
        f"{stylo_result['rationale']}{guard_note}"
    )


def score_submission(llm_result, stylo_result, degraded=False):
    stylo_score = stylo_result["ai_likelihood"]
    short_input_guard = not stylo_result["reliable"]

    if degraded:
        p_ai = p_ai_for_degraded_stylometry(stylo_score, short_input_guard=short_input_guard)
    elif short_input_guard:
        p_ai = p_ai_for_short_input(llm_result["ai_likelihood"])
    else:
        p_ai = combine_scores(llm_result["ai_likelihood"], stylo_score)

    attribution = attribution_from_p_ai(p_ai)
    return {
        "p_ai": p_ai,
        "confidence": confidence_from_p_ai(p_ai),
        "attribution": attribution,
        "label": label_from_attribution(attribution),
        "short_input_guard": short_input_guard,
        "degraded": degraded,
    }


def ensure_log_file():
    DATA_DIR.mkdir(exist_ok=True)
    if not AUDIT_LOG_PATH.exists():
        AUDIT_LOG_PATH.write_text("[]\n", encoding="utf-8")


def read_log_entries():
    ensure_log_file()
    with AUDIT_LOG_PATH.open("r", encoding="utf-8") as log_file:
        return json.load(log_file)


def write_log_entries(entries):
    ensure_log_file()
    with AUDIT_LOG_PATH.open("w", encoding="utf-8") as log_file:
        json.dump(entries, log_file, indent=2)
        log_file.write("\n")


def get_log(limit=None):
    entries = list(reversed(read_log_entries()))
    if limit is not None:
        return entries[:limit]
    return entries


def append_log(entry):
    entries = read_log_entries()
    entries.append(entry)
    write_log_entries(entries)


def find_latest_content_entry(entries, content_id):
    for entry in reversed(entries):
        if entry.get("content_id") == content_id and entry.get("event_type", "submission") == "submission":
            return entry
    return None


def update_content_status(content_id, status, appeal_reasoning):
    entries = read_log_entries()
    original_entry = find_latest_content_entry(entries, content_id)
    if original_entry is None:
        return None

    for entry in entries:
        if entry.get("content_id") == content_id and entry.get("event_type", "submission") == "submission":
            entry["status"] = status
            entry["appeal_reasoning"] = appeal_reasoning

    write_log_entries(entries)
    return deepcopy(original_entry)


@app.post("/submit")
@limiter.limit("10 per minute;100 per day")
def submit():
    payload = request.get_json(silent=True)
    if not isinstance(payload, dict):
        return jsonify({"error": "JSON body is required"}), 400

    text = payload.get("text")
    creator_id = payload.get("creator_id")
    if not isinstance(text, str) or not text.strip():
        return jsonify({"error": "text is required"}), 400
    if not isinstance(creator_id, str) or not creator_id.strip():
        return jsonify({"error": "creator_id is required"}), 400

    try:
        stylo_result = signals.stylo_signal(text)
    except ValueError as error:
        return jsonify({"error": "Signal 2 failed", "details": str(error)}), 400

    llm_latency_ms = None
    degraded = False
    try:
        llm_start = time.perf_counter()
        llm_result = signals.groq_signal(text)
        llm_latency_ms = round((time.perf_counter() - llm_start) * 1000)
    except (SignalError, ValueError) as error:
        degraded = True
        llm_result = {"ai_likelihood": None, "rationale": str(error)}

    scoring = score_submission(llm_result, stylo_result, degraded=degraded)
    reason = reason_from_signals(
        llm_result,
        stylo_result,
        degraded=scoring["degraded"],
        short_input_guard=scoring["short_input_guard"],
    )
    content_id = str(uuid4())
    timestamp = utc_timestamp()

    response = {
        "content_id": content_id,
        "attribution": scoring["attribution"],
        "confidence": scoring["confidence"],
        "label": scoring["label"],
        "reason": reason,
        "timestamp": timestamp,
    }

    append_log(
        {
            "content_id": content_id,
            "creator_id": creator_id,
            "event_type": "submission",
            "timestamp": timestamp,
            "text": text,
            "llm_ai_likelihood": llm_result["ai_likelihood"],
            "stylo_ai_likelihood": stylo_result["ai_likelihood"],
            "stylo_metrics": stylo_result["metrics"],
            "p_ai": scoring["p_ai"],
            "confidence": scoring["confidence"],
            "attribution": scoring["attribution"],
            "label": scoring["label"],
            "reason": reason,
            "llm_latency_ms": llm_latency_ms,
            "degraded": scoring["degraded"],
            "short_input_guard": scoring["short_input_guard"],
            "status": "classified",
            "appeal_reasoning": None,
        }
    )

    return jsonify(response)


@app.post("/appeal")
def appeal():
    payload = request.get_json(silent=True)
    if not isinstance(payload, dict):
        return jsonify({"error": "JSON body is required"}), 400

    content_id = payload.get("content_id")
    creator_reasoning = payload.get("creator_reasoning")
    if not isinstance(content_id, str) or not content_id.strip():
        return jsonify({"error": "content_id is required"}), 400
    if not isinstance(creator_reasoning, str) or not creator_reasoning.strip():
        return jsonify({"error": "creator_reasoning is required"}), 400

    content_id = content_id.strip()
    creator_reasoning = creator_reasoning.strip()
    original_entry = update_content_status(content_id, "under_review", creator_reasoning)
    if original_entry is None:
        return jsonify({"error": "content_id not found"}), 404

    appeal_entry = {
        "event_type": "appeal",
        "content_id": content_id,
        "creator_id": original_entry.get("creator_id"),
        "timestamp": utc_timestamp(),
        "text": original_entry.get("text"),
        "llm_ai_likelihood": original_entry.get("llm_ai_likelihood"),
        "stylo_ai_likelihood": original_entry.get("stylo_ai_likelihood"),
        "stylo_metrics": original_entry.get("stylo_metrics"),
        "p_ai": original_entry.get("p_ai"),
        "confidence": original_entry.get("confidence"),
        "attribution": original_entry.get("attribution"),
        "label": original_entry.get("label"),
        "reason": original_entry.get("reason"),
        "llm_latency_ms": original_entry.get("llm_latency_ms"),
        "degraded": original_entry.get("degraded"),
        "short_input_guard": original_entry.get("short_input_guard"),
        "status": "under_review",
        "appeal_reasoning": creator_reasoning,
    }
    append_log(appeal_entry)

    return jsonify(
        {
            "message": "Appeal received. Status updated to under review.",
            "content_id": content_id,
            "status": "under_review",
        }
    )


@app.get("/log")
def log():
    return jsonify({"entries": get_log()})


if __name__ == "__main__":
    ensure_log_file()
    app.run(host="0.0.0.0", port=5000, debug=True)
